import React, { useState } from "react";
import CardCom from "../../../Component/Card/CardCom";
import bag1 from "../../../../../public/bag1.webp";
import { Grid2X2Icon, Grid3X3Icon } from "lucide-react";
import {
  Grid3x2GapFill,
  Grid3x3GapFill,
  GridFill,
} from "react-bootstrap-icons";
import icon4x4 from "../../../../assets/4x4.png";
let arr = [
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
  {
    id: 1,
    title: "Fitpack Neo",
    category: "Bag",
    price: 499.0,
    image: bag1,
    HoverImage: bag1,
    old_price: 600,
    rating: 4,
    discount: "37%",
  },
];
export default function CommonProduct() {
  let [gridCols, setGridCols] = useState("grid grid-cols-4");
  
  return (
    <div>
      <img src={bag1} className="w-[100%] max-h-[500px]" alt="" />
      <div className="flex justify-end p-3 [&_*]:mr-2 mt-10">
        <GridFill
          className="text-gray-400 text-xl "
          onClick={() => setGridCols("grid grid-cols-2")}
        />
        <Grid3x3GapFill
          className="text-xl text-gray-400 "
          onClick={() => setGridCols("grid grid-cols-3")}
        />
        <img
          src={icon4x4}
          className="h-[20px] !fill-gray-400"
          alt=""
          onClick={() => setGridCols("grid grid-cols-4")}
        />
      </div>
      <hr />
      <div className={gridCols} style={{ padding: "20px" }}>
        {arr.map((e) => {
          return <CardCom data={e} key={e.id} />;
        })}
      </div>
    </div>
  );
}
