import React, { useLayoutEffect } from "react";

export default function PrivacyPolicy() {
  useLayoutEffect(() => {
    window.scrollTo(0, 0);
  });

  return (
    <>
      <h1>test privacy</h1>
      {/* <div className="privacy" style={{ paddingBottom: "80px" }}>
                <div className="container">
                    <div className="privacy_page">
                        <h1 className='pt-5 ps-5 pb-4' style={{ fontSize: "50px", fontWeight: "400" }}>Privacy Policy</h1>
                        <div className='border-bottom border-3 border-black' style={{ width: "6%", marginLeft: "120px" }}></div>
                        <div className='pb-4' style={{ paddingTop: "100px", fontFamily: "'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif" }}>
                            <p>
                                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                            </p>
                            <p>
                                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                            </p>
                            <div>
                                <h1 style={{ fontSize: "50px" }}>Interpretation and Definitions</h1>
                                <h2 className='pt-4'>Interpretation</h2>
                                <p className='pt-4'>
                                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                                </p>
                                <h2>Definitions</h2>
                                <p className='pt-3'>For the purposes of this Privacy Policy:</p>
                                <p>Account means a unique account created for You to access our Service or parts of our Service.</p>
                                <p>
                                    Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                                </p>
                                <p>
                                    Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Layers Electronics Pvt Ltd, 16TH, OFFICE NO 1617, LOGIX CITY CENTRE, SECTOR 32, NOIDA, Gautam Buddha Nagar, Uttar Pradesh, 201301.
                                </p>
                                <p>
                                    Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                                </p>
                                <p>Country refers to: Uttar Pradesh, India</p>
                                <p>
                                    Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                                </p>
                                <p>Personal Data is any information that relates to an identified or identifiable individual.</p>
                                <p>Service refers to the Website.</p>
                                <p>
                                    Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
                                </p>
                                <p>
                                    Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.
                                </p>
                                <p>
                                    Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                                </p>
                                <p>Website refers to Layers, accessible from <ins>https://www.layers.shop/</ins></p>
                                <p>
                                    You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                                </p>
                            </div>
                            <div>
                                <h1>DMCA Notice of Alleged Infringement ("Notice")</h1>
                                <p className='pt-4'>
                                    you are a copyright owner, authorized to act on behalf of one, or authorized to act under any exclusive right under copyright, please report alleged copyright infringements taking place on or through the Site by completing a DMCA Notice of Alleged Infringement and delivering it to Layers’s Designated Copyright Agent. Upon receipt of Notice as described below, Layers will take whatever action, in its sole discretion, it deems appropriate, including removal of the challenged content from the Site. Please note that if you fail to comply with all of the requirements of this section and of 17 USC § 512(c)(3) your DMCA notice may not be valid. Identify the copyrighted work that you claim has been infringed, or - if multiple copyrighted works are covered by your Notice - you may provide a representative list of the copyrighted works that you claim have been infringed. Identify the material or link you claim is infringing (or the subject of infringing activity) and to which access is to be disabled, including at a minimum, if applicable, the URL of the link shown on the Site or the exact location where such material may be found. Provide your company affiliation (if applicable), mailing address, telephone number, and, if available, email address. Include both of the following statements in the body of the Notice: "I hereby state that I have a good faith belief that the disputed use of the copyrighted material is not authorized by the copyright owner, its agent, or the law (e.g., as a fair use)." "I hereby state that the information in this Notice is accurate and, under penalty of perjury, that I am the owner, or authorized to act on behalf of, the owner, of the copyright or of an exclusive right under the copyright that is allegedly infringed." Provide your full legal name and your electronic or physical signature. Deliver this Notice, with all items completed, to Layers’s Designated Copyright Agent: Copyright Agent Layers Office Space No 1617 16th Floor Plot No BW-58, Logix City Centre Sec32 Noida Gautam Buddha Nagar UP 201301 IN.
                                </p>
                            </div>
                            <div>
                                <h1>DMCA Counter-Notice of Alleged Infringement</h1>
                                <p className='pt-3'>
                                    If you believe that your content that was removed (or to which access was disabled) is not infringing, or that you have authorization from the copyright holder, the holder's agent, or pursuant to law, to post and use the material in your content, you may send a Counter-Notice containing the following information to Layers's Copyright Agent: Your physical or electronic signature; Identification of the content that was removed or to which access has been disabled as a result of mistake or a misidentification of the content; and Your name, address, telephone number, and email address, a statement that you consent to the jurisdiction of the federal court in Alachua County, Florida, and a statement that you will accept service of process from the person who provided notification of the alleged infringement. If a Counter-Notice is received by the Copyright Agent, Layers may send a copy of the Counter-Notice to the original complaining party informing that person that it may replace the removed content or cease disabling it in ten business days. Unless the copyright owner files an action seeking a court order against Layers or the person who has posted allegedly infringing content, the removed content may be replaced, or access to it restored, in ten business days or more after receipt of the Counter-Notice. Layers Policy Regarding Repeat Infringers Layers does not condone or tolerate copyright infringement or any violation of the intellectual property rights of Layers or of others. Layers reserves the right to terminate the access and/or use privileges of any person who has been determined to be a 'repeat infringer' of the copyrights of Layers or others. Layers reserves the right to define the criteria by which Layers will determine that a person is a 'repeat infringer.' In the event that repeat infringer' is defined by statute, law, or regulation as applicable to 17 USC § 512, Layers will adopt that definition as a minimum standard. Without limiting Layers’s right to define 'repeat infringer,' as a general rule, Layers will define a 'repeat infringer' as any person or entity about whom Layers has received two or more DMCA Notices of Alleged Infringement. Layers will take into account all relevant facts and circumstances when determining whether or not termination of access and/or use privileges of a 'repeat infringer' is appropriate. REGARDLESS OF WHETHER LAYERS TERMINATES ACCESS AND/OR USE PRIVILEGES OF ANY PERSON OR ENTITY, 'REPEAT INFRINGER' OR OTHERWISE, LAYERS IN NO WAY WAIVES ANY RIGHT TO PURSUE ANY AVAILABLE REMEDY AT LAW OR IN EQUITY AGAINST COPYRIGHT INFRINGERS OR ANY OTHER INTELLECTUAL PROPERTY RIGHTS VIOLATORS, NOR WILL LAYERS INDEMNIFY OR PROVIDE LEGAL REPRESENTATION TO ANY ALLEGED INFRINGER IN ANY ACTION ARISING FROM THE ALLEGED INFRINGER’S USE OF ANY LAYERS WEBSITE OR SERVICE, EXCEPT AS EXPRESSLY DESCRIBED IN THIS NOTICE.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div> */}
    </>
  );
}
